//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DETAIL
    {
        public string NAME { get; set; }
        public string BRANCH { get; set; }
        public int SCORE { get; set; }
        public string DIVISION { get; set; }
        public int ID { get; set; }
    }
}
